_25ju=y
bluetooth=y

drive_dev='/dev/nvme0n1'
hostname='25ju'
interface_wlan='wlan0'

readonly \
    arch_linux audio_hq_resamp bluetooth dns dnsmasq efi_fat env ipv6 kvantum \
    m533ia optimal_lbaf pipewire pipewire_media_session portal root_ext4 sway \
    systemd wayland arch_mirlist block_size drive_dev efi_mnt efi_partition \
    gid group home hostname interface_wlan partitioning_reserve_gib \
    root_partition uid user
