_25ju=
_m533ia=
arch_linux=y
audio_hq_resamp=
bluez=
dns=y
dnsmasq=y
efi_fat=y
env=y
fstab_ext4_journal_async_commit=
fstab_ext4_nobarrier=
fstab_ext4_writeback=
fstab_relatime=
ipv6=
kvantum=y
optimal_lbaf=
root_ext4=y
systemd=y
wayland=y

arch_mirlist='/etc/pacman.d/mirrorlist'
block_size='512'
drive_dev='/dev/nvme0n1'
efi_mnt='/efi'
efi_partition='/dev/nvme0n1p1'
fstab_ext4_commit=''
gid='1000'
group='mscalindt'
home='/home/mscalindt'
hostname='syscfg'
interface_wlan='wlan0'
partitioning_reserve_gib='8'
root_partition='/dev/nvme0n1p2'
uid='1000'
user='mscalindt'
