arch_linux=y
audio_hq_resamp=
bluetooth=
dns=y
dnsmasq=y
efi_fat=y
env=y
fstab_ext4_nobarrier=
fstab_relatime=
ipv6=
kvantum=y
m533ia=
optimal_lbaf=
pipewire=y
pipewire_media_session=y
portal=y
root_ext4=y
sway=y
systemd=y
wayland=y

arch_mirlist='/etc/pacman.d/mirrorlist'
block_size='512'
drive_dev='/dev/nvme0n1'
efi_mnt='/efi'
efi_partition='/dev/nvme0n1p1'
gid='1000'
group='mscalindt'
home='/home/mscalindt'
hostname='syscfg'
interface_wlan='wlan0'
partitioning_reserve_gib='8'
root_partition='/dev/nvme0n1p2'
uid='1000'
user='mscalindt'
